### ISSUE TITLE
Decide how much of a packrat to be

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev-artwork#37]
Do we want to give ourselves an easy way to back out certain asset removals?

1. Za'lek Imp, old Za'lek Mephisto graphics (problem: no models): last reliable reference is probably the parent of https://github.com/naev/naev/commit/35d78ebe1d1d816ed8c0c0845cfcc31a043d2b8b
2. Unused commodity graphics from Vega Strike: we probably want a workflow to re-render even the current ones from the high-res sources in https://github.com/vegastrike/Assets-Masters/tree/master/textures/cargo/sources

List is likely to grow, unless we find a good place to document recoverable assets... or let go.

**Comment by bobbens** [comment]
Mephisto replaced with old prototype solves that right? The issue is the remaining missing ones. I'm fine with removing unneeded assets from other projects, I would be more conservative on the ones that are naev-specific.

**Comment by UncombedCoconut** [comment]
That mostly answers this. But I think the old Mephisto sprite-sheet really was Naev-specific, so there's still the question of whether we want it fully deleted from the repos (except the history of naev/naev).
